
[NEST]

; Detector parameters - XLZD Nominal (WIMP Search Optimized)
temperature_config = 177.0 ; K
pressure_config = 2.0 ; bar
; XLZD DesignBook: 240 and 290 V/cm optimal
drift_field_config = 240.0 ; V/cm
; XLZD DesignBook: 6-8 kV/cm typically
gas_field_config = 6.0 ; kV/cm

; The required total mass of xenon assumes a
; 10cm charge-insensitive reverse field region below the
; cathode, a LXe Skin of 7cm between the TPC walls and
; the cryostat, and takes into account the LXe around
; and below the bottom PMTs.

; Target diameter [cm]: 298
; Target drift length [cm]: 297 (nominal), 396 (opportunity)
; Target mass [tonne]: 60 (nominal), 80 (opportunity)
; FV mass [tonne]: 48 (nominal), 64 (opportunity)
; Total mass [tonne]: 78 (nominal), 104 (opportunity)
z_topDrift_config = 297.0 ; cm
radius_config = 144.0 ; cm
dt_min_config = 6401.797248944392 ; ns
dt_max_config = 1901333.7829364846 ; ns

g1_config = 0.125 ; Hohe Lichtausbeute ist kritisch für niedrige WIMP-Massen
elife_config = 10000000 ; ns

spe_res_config = 0.30
spe_thr_config = 0.35
spe_eff_config = 0.95

; A total of 1182 3-inch PMTs would be needed in the top
; and bottom PMT arrays, respectively -> 2364 total
num_pmts_config = 2364
double_pe_fraction_config = 0.20

; Selection parameters - WIMP Search Optimization
coin_level_config = 3 ; Dreifach-Koinzidenz zur Reduktion von Dark Counts bei großen PMT-Arrays
S1_min_config = 3.0   ; Mindestanzahl an Photonen (S1) für eine saubere Rekonstruktion
S1_max_config = 100.0 ; WIMPs erzeugen meist kleine S1-Signale
S2_min_config = 50.0 ; Entspricht etwa 1-2 extrahierten Elektronen (niedrige Schwelle)
S2_max_config = 10000 ; Obergrenze für typische WIMP-Region

gas_gap_config = 5.0 ; mm
g1_gas_config = 0.1
s2Fano_config = 3.6

S1_noise_config = 0.01 ; Realistisches Rauschen für die Hintergrundmodellierung
S2_noise_config = 0.01
